object Versions {
    const val coreKtxVersion = "1.9.0"
    const val lifecycleRuntimeKtxVersion = "2.6.2"
    const val activityComposeVersion = "1.8.2"
    const val composeBomVersion = "2023.03.00"
    const val junitVersion = "4.13.2"
    const val junitExtVersion = "1.1.5"
    const val espressoCoreVersion = "3.5.1"
    const val appCompactVersion = "1.6.1"
    const val hilt = "2.44"
    const val hiltAndroidCompilerVersion = "2.44"
    const val hiltCompilerVersion = "1.0.0"
    const val hiltNavigationComposeVersion = "1.0.0"
    const val lifecycleVersion = "2.6.2"
    const val material3 = "1.1.2"
    const val retrofitVersion = "2.9.0"
    const val okHttpVersion = "4.12.0"
    const val gsonConverterVersion = "2.9.0"
    const val moshiVersion = "1.14.0"
    const val moshiConverterVersion = "2.9.0"
    const val loggingIntercepterVersion = "4.12.0"
}